title = "Gitleaks Configuration"

[[rules]]
description = "Generic API Key"
regex = '''(?i)apikey[\s:=]+[0-9a-zA-Z]{32,64}'''
tags = ["apikey"]

[[rules]]
description = "Generic Secret"
regex = '''(?i)secret[\s:=]+[0-9a-zA-Z]{32,64}'''
tags = ["secret"]

[[rules]]
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
description = "AWS Secret Key"
regex = '''(?i)aws_secret_access_key[\s:=]+[0-9a-zA-Z/+]{40}'''
tags = ["aws", "secret"]

[[rules]]
description = "Private Key"
regex = '''-----BEGIN (RSA|DSA|EC) PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
description = "Password in URL"
regex = '''https?:\/\/[^\/\s]+:[^\/\s]+@[^\/\s]+'''
tags = ["url", "password"]

# Add more custom rules as needed

[[allowlist]]
description = "Allowlist example"
regexes = ["example1", "example2"]
files = ["examplefile"]

[[allowlist]]
description = "Exclude specific files"
files = ["README.md", "docs/*"]

[[allowlist]]
description = "Exclude specific paths"
paths = ["node_modules", "vendor"]
